env: "local"
storage_path: "user=postgres password=postgres dbname=main sslmode=disable"
http_server:
  address: "0.0.0.0:8081"
  timeout: 5s
  idle_timeout: 75s
kafka:
  address: "localhost:29092"
  url-topic: "url-topic"
redis:
  address: "localhost:6379"